
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xinvert.h"

/*
* The configuration table for devices
*/

XInvert_Config XInvert_ConfigTable[XPAR_XINVERT_NUM_INSTANCES] =
{
	{
		XPAR_INVERT_0_DEVICE_ID,
		XPAR_INVERT_0_S_AXI_CONTROL_BASEADDR
	}
};


